Add CI test builds, fix consistency of software and hardware rendering results (#1)
* Create build.yml

* Update workflow and build scripts

* Update linux_build.bash

* Update linux_build.bash

* Update and rename linux_build.yml to build.yml

* Fix build scripts

* Install dependencies

* Add more dependencies

* Add more dependencies

* Add `fail-fast: false`

* Add Qt dependencies

* Fix build.yml

* Fix build.yml

* Fix build.yml

* Fix build.yml

* Install Qt5 instead of Qt4

* Fix build.yml

* Add libboost-all-dev dependency

* Add `QT_QPA_PLATFORM: offscreen`

* Replace `libboost-all-dev` by `libboost-iostreams-dev`

* Update .github/workflows/build.yml

* Fix `C7528` error

Fix error:

> Shader Compilation Error: Shader compilation has failed.
> 0(15) : error C7528: OpenGL reserves names starting with 'gl_': gl_FragColor

* Employ xvfb-run

* Employ mxschmitt/action-tmate

* Employ actions/upload-artifact

* Remove `QT_QPA_PLATFORM`

* Clean up workflow

* Add `--server-args`

* Update workflow

* Update workflow

* Update workflow

* Fix linux_build.bash

* Add `GL_DEPTH_BUFFER_BIT`

* Use `Sampler.FILTER_NEAREST` in `MaskRenderingStage`

* Clean up code

* Clean up code

* Use `Sampler::FILTER_LINEAR` for colormap in DVRStage.cpp

* Revert "Use `Sampler::FILTER_LINEAR` for colormap in DVRStage.cpp"

This reverts commit bcce78358af55ebee9376d758e7db90e032a7297.

* Update test/res/renderings/DVRStageTest/withoutLighting.png

* Update README.md

* Update README.md

* Update README.md

* Update build.yml

* Update README.md

* Update README.md

* Update build.yml